# References:
#   https://github.com/actions/runner-images
#   https://github.com/nodejs/release#release-schedule
#   https://github.com/actions/checkout
#   https://github.com/actions/setup-node
#   https://github.com/google/wireit?tab=readme-ov-file#github-actions-caching

name: Test (Node)

on: [push, pull_request]

jobs:
  test-node:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # All supported Node versions on latest Linux.
          - node: 18 # Maintenance
            os: ubuntu-24.04
          - node: 20 # Maintenance
            os: ubuntu-24.04
          - node: 22 # LTS
            os: ubuntu-24.04
          - node: 23 # Current
            os: ubuntu-24.04

          # Oldest and newest supported Node versions on latest macOS.
          - node: 18
            os: macos-15
          - node: 23
            os: macos-15

          # Oldest and newest supported Node versions on latest Windows.
          - node: 18
            os: windows-2022
          - node: 23
            os: windows-2022

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v2

      - run: npm ci
      - run: npm run test:node
